server:
  port: 3000
db:
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password:  ""
  database: "ailink"
site:
  password: "admin"
  host: "https://www.ttalk.im"
  name: "TTalkIM"
  jwt: "jwtKey"
  csrf:  "1234567812345678"
github:
  client_id: ""
  client_secret: ""